### ISSUE TITLE
Failure to install helm chart

### ISSUE THREAD

**Issue by patrocinio** [jesusmah/stocktrader-resiliency#3]
When I run the command `helm install -n st-db2 --namespace stocktrader --tls ibm-charts/ibm-db2oltp-dev -f db2_values.yaml`, I am getting the following error:
```
patro:middleware edu$ helm install -n st-db2 --namespace stocktrader --tls ibm-charts/ibm-db2oltp-dev -f db2_values.yaml
Error: Not authorized: Client is not authorized to install a release, into namespace:
st-db2 stocktrader
```

I am using ICP 2.1.0.3.
It seems I need to configure some permission for my user to install a Helm release.

**Comment by jkwong888** [comment]
the user you run `bx pr cluster-config` matters as the CN for the helm client certificate generate will include your username.  This user must be a cluster administrator.

i have also seen this error when tiller in ICP cannot contact or get a response from the auth-idp service to list the teams/roles that the user is assigned to.  This one is harder to solve, you could try to restart auth-idp a few times.

finally, if you use the ICP catalog UI to install instead of helm install, it bypasses all of the above components.

**Comment by patrocinio** [comment]
Hello @jkwong888 I am a single user for the entire environment (admin). 
So it seems it's a problem between tiller and auth-idp.
Thanks!

**Comment by patrocinio** [comment]
I just reinstalled ICP and continue having the same issue.

It's ridiculous that I have to restart auth-idp to make a `helm install` to work...

**Comment by jesusmah** [comment]
@patrocinio apparently there is a fix pack that might resolve your issues:

https://github.ibm.com/IBMPrivateCloud/docs/blob/2.1.0.3_english_only/readmes/patch-readmes/icp_2103_FP1_readme.md#install_fp

more precisely:

https://github.ibm.com/IBMPrivateCloud/docs/blob/2.1.0.3_english_only/readmes/patch-readmes/icp_2103_FP1_readme.md#tiller-and-helm-updates

thanks to @jkwong888

**Comment by patrocinio** [comment]
@jesusmah 

Where can I download the 2.1.0.3 FP1?

Thanks

**Comment by jesusmah** [comment]
Not sure to be honest... a google search pointed me to Fix Central:

https://www-945.ibm.com/support/fixcentral/swg/selectFixes?product=ibm%2FWebSphere%2FIBM+Cloud+Private&fixids=icp-2.1.0.3-build497276&source=dbluesearch&function=fixId&parent=ibm/WebSphere

@jkwong888 do you know here FP can be downloaded from?

**Comment by patrocinio** [comment]
Problem fixed after re-installing ICP environment
